# Generated by Django 4.0.10 on 2024-07-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrthodoxDrug',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('cas_number', models.CharField(blank=True, db_column='cas-number', max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('groups', models.CharField(blank=True, max_length=255, null=True)),
                ('general_references', models.TextField(blank=True, null=True)),
                ('synthesis_reference', models.TextField(blank=True, null=True)),
                ('indication', models.TextField(blank=True, null=True)),
                ('pharmacodynamics', models.TextField(blank=True, null=True)),
                ('mechanism_of_action', models.TextField(blank=True, null=True)),
                ('toxicity', models.TextField(blank=True, null=True)),
                ('metabolism', models.TextField(blank=True, null=True)),
                ('absorption', models.TextField(blank=True, null=True)),
                ('half_life', models.CharField(blank=True, max_length=50, null=True)),
                ('protein_binding', models.CharField(blank=True, max_length=50, null=True)),
                ('route_of_elimination', models.TextField(blank=True, null=True)),
                ('volume_of_distribution', models.CharField(blank=True, max_length=50, null=True)),
                ('clearance', models.CharField(blank=True, max_length=50, null=True)),
                ('classification_description', models.TextField(blank=True, null=True)),
                ('direct_parent', models.CharField(blank=True, max_length=255, null=True)),
                ('kingdom', models.CharField(blank=True, max_length=255, null=True)),
                ('superclass', models.CharField(blank=True, max_length=255, null=True)),
                ('drug_class', models.CharField(blank=True, max_length=255, null=True)),
                ('subclass', models.CharField(blank=True, max_length=255, null=True)),
                ('salts', models.TextField(blank=True, null=True)),
                ('synonyms', models.TextField(blank=True, null=True)),
                ('products', models.TextField(blank=True, null=True)),
                ('international_brands', models.TextField(blank=True, null=True)),
                ('mixtures', models.TextField(blank=True, null=True)),
                ('packagers', models.TextField(blank=True, null=True)),
                ('manufacturers', models.TextField(blank=True, null=True)),
                ('prices', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('affected_organisms', models.TextField(blank=True, null=True)),
                ('dosages', models.TextField(blank=True, null=True)),
                ('atc_codes', models.TextField(blank=True, null=True)),
                ('ahfs_codes', models.TextField(blank=True, null=True)),
                ('pdb_entries', models.TextField(blank=True, null=True)),
                ('patents', models.TextField(blank=True, null=True)),
                ('food_interactions', models.TextField(blank=True, null=True)),
                ('drug_interactions', models.TextField(blank=True, null=True)),
                ('sequences', models.TextField(blank=True, null=True)),
                ('experimental_properties', models.TextField(blank=True, null=True)),
                ('external_identifiers', models.TextField(blank=True, null=True)),
                ('external_links', models.TextField(blank=True, null=True)),
                ('pathways', models.TextField(blank=True, null=True)),
                ('reactions', models.TextField(blank=True, null=True)),
                ('snp_effects', models.TextField(blank=True, null=True)),
                ('snp_adverse_effects', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'OrthodoxDrug',
            },
        ),
        migrations.CreateModel(
            name='TraditionalDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(blank=True, db_column='Product Name', max_length=100, null=True)),
                ('Active_Ingredient', models.CharField(blank=True, db_column='Active Ingredient', max_length=1000, null=True)),
                ('Disease_Indications', models.CharField(blank=True, db_column='Disease Indications', max_length=1000, null=True)),
                ('Scientific_Literature_Reference', models.CharField(blank=True, db_column='Scientific Literature Reference', max_length=1000, null=True)),
                ('Adverse_Effects', models.CharField(blank=True, db_column='Adverse Effects', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'TraditionalDrug',
            },
        ),
    ]
