# Generated by Django 4.0.10 on 2024-04-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraditionalDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'TraditionalDrug',
            },
        ),
        migrations.AddField(
            model_name='orthodoxdrug',
            name='description',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orthodoxdrug',
            name='manufacturers',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
