# Generated by Django 4.0.10 on 2024-05-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugInfo', '0004_remove_orthodoxdrug_absorption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traditionaldrug',
            name='Active_Ingredient',
            field=models.CharField(blank=True, default='Not Specified', max_length=1000, null=True),
        ),
    ]
