# Generated by Django 4.0.10 on 2024-05-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugInfo', '0006_alter_traditionaldrug_active_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthodoxdrug',
            name='cas_number',
            field=models.CharField(blank=True, db_column='cas-number', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='traditionaldrug',
            name='Active_Ingredient',
            field=models.CharField(blank=True, default='Not Specified', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='traditionaldrug',
            name='Adverse_Effects',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='traditionaldrug',
            name='Disease_Indications',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='traditionaldrug',
            name='Product_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='traditionaldrug',
            name='Scientific_Literature_Reference',
            field=models.CharField(blank=True, db_column='Scientific Literature Reference', max_length=1000, null=True),
        ),
    ]
