# Generated by Django 4.0.10 on 2024-03-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('nurse', 'Nurse'), ('doctor', 'Doctor'), ('lab', 'Lab Personnel'), ('pharmacist', 'Pharmacist')], max_length=10, null=True),
        ),
    ]
