# Generated by Django 4.0.10 on 2024-03-20 00:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Diagnosis',
            new_name='Diagnose',
        ),
    ]
