# Generated by Django 4.0.10 on 2024-06-12 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TradDrug',
            new_name='TraditionalDrug',
        ),
    ]
