# Generated by Django 4.0.10 on 2024-03-20 19:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_rename_diagnosis_diagnose'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnose',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
