# Generated by Django 4.0.10 on 2024-06-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_rename_traddrug_traditionaldrug'),
    ]

    operations = [
        migrations.AddField(
            model_name='traditionaldrug',
            name='scientific_literature_reference',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
