# Generated by Django 4.0.10 on 2024-06-14 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_traditionaldrug_scientific_literature_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traditionaldrug',
            name='disease_indications',
            field=models.CharField(max_length=300),
        ),
    ]
