# Generated by Django 4.0.10 on 2024-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_alter_traditionaldrug_disease_indications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traditionaldrug',
            name='scientific_literature_reference',
            field=models.CharField(max_length=1000),
        ),
    ]
