# Generated by Django 4.0.10 on 2024-06-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_alter_traditionaldrug_scientific_literature_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traditionaldrug',
            name='active_ingredient',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='traditionaldrug',
            name='adverse_effects',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='traditionaldrug',
            name='disease_indications',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='traditionaldrug',
            name='product_name',
            field=models.CharField(max_length=1000),
        ),
    ]
