# Generated by Django 4.0.10 on 2024-03-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_diagnose_diagnosis_id_alter_patient_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnose',
            name='diagnosis_id',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
