# Generated by Django 4.0.10 on 2024-06-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_alter_traditionaldrug_active_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traditionaldrug',
            name='active_ingredient',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='traditionaldrug',
            name='adverse_effects',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='traditionaldrug',
            name='disease_indications',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='traditionaldrug',
            name='product_name',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='traditionaldrug',
            name='scientific_literature_reference',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
