# Generated by Django 4.0.10 on 2024-04-10 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_diagnose_selected_drug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnose',
            options={'ordering': ['id']},
        ),
    ]
