# Generated by Django 4.0.10 on 2024-04-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0008_alter_diagnose_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='diagnose',
            name='orthodox_drug_ids',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='diagnose',
            name='traditional_drug_ids',
            field=models.TextField(blank=True),
        ),
    ]
