# Generated by Django 4.0.10 on 2024-07-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0009_report_created_at_report_doctor_report_patient_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diagnosis',
            name='selected_drug',
        ),
    ]
