# Generated by Django 4.0.10 on 2024-05-31 11:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('histories', '0006_alter_history_options'),
        ('recommendations', '0009_alter_patient_options_diagnose_orthodox_drug_ids_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradDrug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=1000)),
                ('disease_indications', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Diagnose',
            new_name='Diagnosis',
        ),
    ]
