# Generated by Django 4.0.10 on 2024-05-31 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0010_traddrug_rename_diagnose_diagnosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosis',
            old_name='diagnosis_id',
            new_name='diagnosis_identifier',
        ),
    ]
