# Generated by Django 4.0.10 on 2024-07-10 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0010_alter_report_id'),
        ('recommendations', '0011_alter_diagnosis_id_alter_report_id'),
    ]

    operations = [
    ]
