# Generated by Django 4.0.10 on 2024-07-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0012_merge_20240710_1939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='selected_drug',
            new_name='selected_traditional_drug',
        ),
        migrations.AddField(
            model_name='report',
            name='selected_orthodox_drug',
            field=models.CharField(default='No Orthodox drug selected', max_length=100),
            preserve_default=False,
        ),
    ]
