# Generated by Django 4.0.10 on 2024-07-14 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0013_rename_selected_drug_report_selected_traditional_drug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='selected_orthodox_drug',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='selected_traditional_drug',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendations.traditionaldrug'),
        ),
    ]
