# Generated by Django 4.0.10 on 2024-07-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0014_alter_report_selected_orthodox_drug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='selected_traditional_drug',
        ),
        migrations.AddField(
            model_name='report',
            name='selected_traditional_drug',
            field=models.ManyToManyField(to='recommendations.traditionaldrug'),
        ),
    ]
