# Generated by Django 4.0.10 on 2024-07-27 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0016_vitals_remove_patient_weight_diagnosis_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='vitals',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recommendations.vitals'),
            preserve_default=False,
        ),
    ]
