# Generated by Django 4.0.10 on 2024-07-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0018_vitals_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='diagnosis',
        ),
        migrations.AddField(
            model_name='report',
            name='diagnosis',
            field=models.ManyToManyField(to='recommendations.diagnosis'),
        ),
    ]
