# Generated by Django 4.0.10 on 2024-03-20 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0003_diagnose_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_made', models.TextField(default='')),
                ('doctor_name', models.CharField(default='', max_length=75)),
                ('doctor_email', models.EmailField(default='', max_length=254)),
                ('doctor_phone', models.CharField(default='', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.diagnose')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendations.patient')),
            ],
        ),
    ]
