# Generated by Django 4.0.10 on 2024-06-12 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_made', models.TextField()),
                ('selected_drug', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=75)),
                ('doctor_phone', models.CharField(max_length=15)),
                ('doctor_email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.diagnosis')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.patient')),
            ],
        ),
    ]
