# Generated by Django 4.0.10 on 2024-03-21 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_diagnose_created_at'),
        ('histories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='patient',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='recommendations.patient'),
            preserve_default=False,
        ),
    ]
