# Generated by Django 4.0.10 on 2024-04-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0002_alter_history_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='selected_drugs',
            field=models.CharField(default='No drug selected at the time', max_length=250),
            preserve_default=False,
        ),
    ]
