# Generated by Django 4.0.10 on 2024-04-10 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0003_history_selected_drugs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='selected_drugs',
        ),
    ]
