# Generated by Django 4.0.10 on 2024-04-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0004_remove_history_selected_drugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='selected_drug',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
