# Generated by Django 4.0.10 on 2024-05-30 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0005_history_selected_drug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['created_at']},
        ),
    ]
